activities/urls.py
from django.urls import path

from activities import views

app_name="activities"

urlpatterns = [
    path("", views.ActivityListView.as_view(), name="list"),
    path("<int:pk>/", views.ActivityDetailView.as_view(), name="detail"),
    path("<int:activity_pk>/comment/new", views.CommentCreateView.as_view(), name="comment_new"),
    path("<int:activity_pk>/comment/<int:pk>/edit", views.CommentUpdateView.as_view(), name="comment_edit"),
    path("<int:activity_pk>/comment/<int:pk>/delete", views.CommentDeleteView.as_view(), name="comment_delete"),
    path("<int:activity_pk>/regist/", views.regist, name="regist"),
    path("<int:activity_pk>/regist/delete", views.delete_regist, name="delete_regist"),
    path("<int:activity_pk>/likes/", views.likes, name="likes"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import get_user_model
from django.template.defaulttags import url
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("activities/", include("activities.urls")),
    path("", RedirectView.as_view(pattern_name="activities:list"), name="root"),
    # DRF
    # path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from rest_framework import routers, serializers, viewsets

# Serializers define the API representation.

User = get_user_model()
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns += [path('api/', include(router.urls))]

templates/include/ajax.html
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script type="text/javascript">
        function post_like(id) {
            console.log("hi")
            $.ajax({
                url: "{%url 'activities:likes' activity.pk%}", // data를 전송할 url 입니다.
                data: {
                    'activity_id': id
                }, // activity_id 라는 name으로 id 값 전송
                dataType: "json",
                success: function (response) { // ajax 통신이 정상적으로 완료되었을 때
                    $('#like_count').html(response.like_count) //id가 like_count의 내용을 전송받은 좋아요 수로 바꾼다
                    if (response.message == "good")
                    //좋아요 눌렀을 때
                    {
                        $('#heart_btn').attr("class", "btn btn-dark rounded")
                        $('#heart').attr("class", "fas fa-heart")
                        $('#heart').css("color", "red")
                    } else if (response.message == "notgood")
                    //좋아요 상태에서 다시 눌렀을 때
                    {
                        $('#heart_btn').attr("class", "btn btn-dark rounded")
                        $('#heart').attr("class", "far fa-heart")
                        $('#heart').css("color", "white")
                    }
                }
            })
        }
    </script>