activities/urls.py
from django.urls import path

from activities import views

app_name="activities"

urlpatterns = [
    path("", views.ActivityListView.as_view(), name="list"),
    path("<int:pk>/", views.ActivityDetailView.as_view(), name="detail"),
    path("<int:activity_pk>/comment/new", views.CommentCreateView.as_view(), name="comment_new"),
    path("<int:activity_pk>/comment/<int:pk>/edit", views.CommentUpdateView.as_view(), name="comment_edit"),
    path("<int:activity_pk>/comment/<int:pk>/delete", views.CommentDeleteView.as_view(), name="comment_delete"),
    path("<int:activity_pk>/regist/", views.regist, name="regist"),
    path("<int:activity_pk>/regist/delete", views.delete_regist, name="delete_regist"),
    path("<int:activity_pk>/likes/", views.likes, name="likes"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import get_user_model
from django.template.defaulttags import url
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("activities/", include("activities.urls")),
    path("", RedirectView.as_view(pattern_name="activities:list"), name="root"),
    # DRF
    # path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from rest_framework import routers, serializers, viewsets

# Serializers define the API representation.

User = get_user_model()
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns += [path('api/', include(router.urls))]

activities/models.py
from django.conf import settings
from django.db import models
from django.db.models import ForeignKey, OneToOneField

class Photo(models.Model):
    """ Photo Model Definition """

    caption = models.CharField(max_length=100)
    file = models.ImageField(upload_to="activity_photos")
    activity = models.ForeignKey("Activity", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption

class Activity(models.Model):
    title=models.CharField(max_length=50)
    description=models.TextField()
    master=models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    liked_user_set = models.ManyToManyField(
        settings.AUTH_USER_MODEL, blank=True, related_name="likes"
    )

    class Meta:
        verbose_name_plural = "Activities"

    def __str__(self):
        return self.title

    def first_photo(self):
        try:
            (photo,) = self.photo_set.all()[:1]
            return photo.file.url
        except ValueError:
            return None

    def get_all_photos(self):
        photos = self.photo_set.all()
        return photos

class Registration(models.Model):
    user_regist=OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    activity_regist=ForeignKey("Activity", on_delete=models.CASCADE, related_name="registrations", blank=True, null=True)

    def __str__(self):
        return f"{self.activity_regist} - {self.user_regist}"

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    activity = models.ForeignKey("Activity", on_delete=models.CASCADE)
    content = models.TextField()
    like = models.PositiveIntegerField(default=0, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

activities/forms.py
from django import forms

from activities.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields=[
            "content",
        ]
        widgets = {
            "content": forms.Textarea(attrs={"rows": 2})
        }

activities/views.py
import json
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from activities.forms import CommentForm
from activities.models import Comment, Activity, Registration


class ActivityListView(ListView):

    """ Activity List View Definition"""

    model = Activity
    ordering = "id"
    context_object_name = "activities"

    def get(self, request, *args, **kwargs):
        activities_qs = self.get_queryset()
        regists_qs = [Registration.objects.filter(activity_regist_id=activity.pk).count() for activity in activities_qs]
        activities_regists = zip(activities_qs,regists_qs)
        return render(request, "activities/activity_list.html", {'activities_regists': activities_regists})



class ActivityDetailView(DetailView):

    """ Activity Detail View Definition """

    model = Activity

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        activity_pk = self.kwargs['pk']
        current_regist = Registration.objects.filter(user_regist_id=self.request.user.id)
        qs = Registration.objects.filter(activity_regist_id=activity_pk)
        context_data["registration_count"] = qs.count()
        context_data["registration_user_id_set"] = [i.user_regist_id for i in qs]
        context_data["current_regist"] = bool(current_regist)
        context_data["comment_form"] = CommentForm()
        return context_data

@login_required
def regist(request, activity_pk):
    user_id = request.user.id
    Registration.objects.create(
        user_regist_id=user_id,
        activity_regist_id=activity_pk
    )
    return redirect(resolve_url("activities:detail", activity_pk))

def user_check(user):
    return user.pk == user.registration.user_regist_id

@user_passes_test(user_check)
def delete_regist(request, activity_pk):
    Registration.objects.filter(
        user_regist_id=request.user.id,
        activity_regist_id=activity_pk,).delete()
    print('>>>>>>>>',Registration.objects.all())
    return redirect(resolve_url("activities:detail", activity_pk))




class CommentCreateView(LoginRequiredMixin, CreateView):

    """ Comment Create View Definition """

    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.author = self.request.user
        comment.activity = get_object_or_404(Activity, pk=self.kwargs["activity_pk"])
        response = super().form_valid(form)
        return response

    def get_success_url(self):
        return resolve_url("activities:detail", self.kwargs["activity_pk"])
        # return reverse("activities:detail", kwargs={'pk': self.kwargs["activity_pk"]})

class CommentUpdateView(UserPassesTestMixin, UpdateView):

    """ Comment Update View Definition """

    model = Comment
    form_class = CommentForm
    template_name = "form.html"

    def test_func(self):
        return self.request.user == self.get_object().author

    def get_success_url(self):
        return resolve_url("activities:detail", self.kwargs["activity_pk"])

class CommentDeleteView(UserPassesTestMixin, DeleteView):

    """ Comment Delete View Definition """

    model = Comment

    def test_func(self):
        return self.request.user == self.get_object().author

    def get_success_url(self):
        return resolve_url("activities:detail", self.kwargs["activity_pk"])

def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'
@login_required()
def likes(request, activity_pk):
    if is_ajax(request):
        activity = Activity.objects.get(id=activity_pk)
        user = request.user
        if activity.liked_user_set.filter(id = user.id).exists():
            activity.liked_user_set.remove(user)
            message="notgood"
        else:
            activity.liked_user_set.add(user)
            message="good"
        context={'like_count':activity.liked_user_set.count(),
                 'message':message}
        return HttpResponse(json.dumps(context), content_type="application/json")

templates/activities/activity_detail.html
{% extends "base.html" %}
{% load bootstrap5 %}


{% block content %}
    <div class="row row-cols-2 h-100">
        <div class="col-6">
            {% for photo in activity.get_all_photos  %}
            <div
                    style="background-image:url({{photo.file.url}});background-size: cover;box-shadow:inset 0 0 0 150vw rgba(0,0,0,0.4);background-position-x: center;background-position-y: center;"
                    class="rounded w-100 h-100 d-flex flex-column align-items-center justify-content-between">
                    <div class="w-75 d-flex flex-row justify-content-between ml-2 mr-4">
                        <div class="d-flex-inline">
                          <button id="heart_btn" onclick="post_like(this.id)" class="btn btn-dark rounded">
                                  {%if request.user in activity.liked_user_set.all%}
                                  <!-- 로그인 한 유저가 좋아요를 누른 유저일때  -->
                                    <i id="heart" class="red-text fas fa-heart" style="color:red"></i>
                                  {%else%}
                                  <!-- 로그인 한 유저가 좋아요를 누른 유저가 아닐 때  -->
                                    <i id="heart" class="far fa-heart"></i>
                                  {%endif%}
                                  <span id="like_count">{{activity.liked_user_set.count}}</span>
                          </button>
                        </div>
                        <div class="d-flex text-white align-items-center">
                            현재인원 {{ registration_count|add:1 }}
                        </div>
                    </div>
                    <div class="text-white d-flex-inline text-center">
                        <div class= text-white">
                            <h2 class="sd-inline-block card-title">{{activity.title }}</h2>
                            <i>by {{ activity.master }}</i>
                        </div>
                    </div>
                    {% if user.id == activity.master_id %}
                        <button class="rounded w-75 btn btn-dark mb-5 disabled">신청완료</button>
                    {% elif user.id in registration_user_id_set %}
                        <a href="{% url "activities:delete_regist" activity.pk %}" class="rounded w-75 btn btn-danger mb-5">신청취소</a>
                    {% elif current_regist %}
                        <button class="rounded w-75 btn btn-dark mb-5 disabled">이미 신청하셨습니다</button>
                    {% else %}
                        <a href="{% url "activities:regist" activity.pk %}" class="rounded w-75 btn btn-primary mb-5">신청하기</a>
                    {% endif %}
            </div>
            {% endfor %}
        </div>
        <div class="col-6">
            <p>댓글 ({{ activity.comment_set.all.count }})</p>

            <div class="comment-list">
                {% for comment in activity.comment_set.all %}
                    {{ page_obj }}
                    <div class="card mb-4">
                      <div class="card-body">
                          <div class="d-flex flex-row justify-content-between">
                              <div class="justify-content-start">
                                <p>{{ comment.content|linebreaks }}</p>
                              </div>
                              <div class="justify-content-end">
                                  {% if user == comment.author %}
                                      <a href="{% url "activities:comment_edit" activity.pk comment.pk %}" class="btn btn-outline-info">수정하기</a>
                                  {% endif %}
                              </div>
                          </div>
                          <div class="d-flex justify-content-between">
                          <div class="d-flex flex-row align-items-center">
                            <img src="https://thumbs.dreamstime.com/b/person-icon-creative-trendy-colorful-round-button-illustration-isolated-156511182.jpg" alt="avatar" width="25"
                              height="25" />
                            <p class="small mb-0 ms-2">작성자: {{ comment.author }}</p>
                          </div>
                              <div class="d-flex flex-row align-items-center">
                                  {% if user == comment.author %}
                                      <a href="{% url "activities:comment_delete" activity.pk comment.pk %}" class="btn btn-outline-danger">삭제하기</a>
                                  {% endif %}
                          </div>
                        </div>
                      </div>
                    </div>
                {% endfor %}
            </div>

            <form action="{% url "activities:comment_new" activity.pk %}" method="post" novalidate>
                {% csrf_token %}
                {% bootstrap_form comment_form layout="inline" %}
                <input type="submit" value="저장" class="btn btn-danger mt-2" />
            </form>
        </div>
    </div>
{% endblock %}

{% block extra-script %}
    {% include 'include/ajax.html' %}
{% endblock %}

templates/activities/activity_list.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block content %}
    <div class="row row-cols-3 h-100">
    {% for activity, regist_cnt in activities_regists %}
        <div class="col mb-1">
{#            <h5 class="d-inline-block card-title bg-dark bg-opacity-75">{{ activity.title }}</h5>#}
            <a href="{% url "activities:detail" activity.pk %}">
              <div class="h-100 img-fluid img-thumbnail d-flex align-items-center justify-content-center " style="background-image: url({{ activity.first_photo }}); background-size: cover;background-position-x: center;background-position-y: center;">
                <div class="text-white d-flex-inline text-center">
                    <div>
{#                        <div class="d-flex-inline bg-dark bg-opacity-75 text-white">현재인원 {{ regist_cnt|add:1 }}</div>#}
{#                        <div class="d-flex-inline bg-dark bg-opacity-75 text-white">좋아요: {{activity.liked_user_set.count}}</div>#}
                        <h5 class="d-inline-block card-title bg-dark bg-opacity-75 text-white">{{activity.title }}</h5>
                    </div>
                </div>
              </div>
            </a>
        </div>
    {% endfor %}
    </div>

{% endblock %}