accounts/urls.py
from django.urls import path

from accounts import views

app_name="accounts"

urlpatterns = [
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("login/", views.MyLoginView.as_view(), name="login"),
    path("logout/", views.MyLogoutView.as_view(), name="logout"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/edit", views.ProfileUpdateView.as_view(), name="profile_edit"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import get_user_model
from django.template.defaulttags import url
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("activities/", include("activities.urls")),
    path("", RedirectView.as_view(pattern_name="activities:list"), name="root"),
    # DRF
    # path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from rest_framework import routers, serializers, viewsets

# Serializers define the API representation.

User = get_user_model()
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns += [path('api/', include(router.urls))]

templates/base.html
{% load bootstrap5 %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>K5 Day</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <style>
        html,body{
            height: 100%;
        }
    </style>
</head>
<body>
<div class="container h-100">
    <nav class="navbar navbar-expand-lg navbar-light">
            <a href="{% url 'root' %}" class="navbar-brand">
                <i class="fa-brands fa-python text-primary me-1"></i>
                <B>K5 Day</B>
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
                <div class="navbar-nav gap-2">



                    {% if user.is_authenticated %}
                            <a href="{% url "accounts:profile" %}" class="btn btn-outline-info rounded">{{ user }}'s Profile</a>
                            <a href="{% url "accounts:logout" %}" class="btn btn-outline-success">로그아웃</a>
                    {% else %}
                        {% url 'accounts:login' as login_path %}
                        {% if not request.path == login_path %}
                            <a href="{% url "accounts:login" %}" class="btn btn-outline-danger">로그인</a>
                            <a href="{% url "accounts:signup" %}" class="btn btn-outline-secondary">회원가입</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </nav>
        <hr>
        <div class="card h-75">
            <div class="card-body">
                {% block content %}
                {% endblock %}
            </div>
        </div>

    <hr>
    &copy; 2022 Pythonistar
</div>
{% block extra-script %}{% endblock %}
</body>
</html>

templates/form.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <input type="submit" class="btn btn-danger">
        {% endbuttons %}
    </form>
{% endblock %}